package com.example.demo.entities.enums;

public enum Measures {
    POLITICAL_FAIRNESS, POLSBYPOPPER_COMPACTNESS, POPULATIONFATNESS_COMPACTNESS,
    GRAPH_COMPACTNESS,POPULATION_EQUALITY,DEVIATION_FROM_ENACTEDAREA,DEVIATION_FROM_ENACTEDPOP,
    SPLIT_COUNTIES
    }
